name = "Default Template"
builder = "spa"
version = "1.0.2"
author = "Konrad Wasowicz (exaroth@gmail.com)"

[template_settings]
text-color = "#c7cfcc"
highlight-color = "#73bed3"
accent-color = "#3c5e8b"
background-color = "#181818"
