# This denotes root path to the feed page.
# If hosted as a github project page this should
# be set to '/<project-name>/', unless the page is
# hosted as default page for the user 
# (eg <username>.github.io), in that case it should be
# set to '/'
site_path = "/liveboat-github-runner/"
# Title of the site
title = "Liveboat Demo"
# Maximum number of days for which Liveboat will include
# articles for.
time_threshold = 40
# This denotes whether articles marked as read by Newsboat
# should be included on the page.
show_read_articles = true
# Below variables define default directories 
# and typically should not be changed.
newsboat_urls_file = "./config/newsboat-urls"
newsboat_cache_file = "./cache.db"
build_dir = "./docs"
